### PR TITLE
Feature/compare

### PR DESCRIPTION
**Pull request by jwsi**
Hey Ben,

Finally the PR is ready! Here is a summary of the completed changes thus far:

- Add dedicated compare page.
- Experiments dynamically update based on target selection.
- Based on target and experiment selection, analaysis results (correlation & t-test) dynamically update.
- Checkbox selection of any combination of analyis results will produce a matplotlib modal alert when the "Plot Selected Results" button is pressed. This can be downloaded as a PNG too.
- Within the popup results modal, a share button is introduced to allow quick and easy sharing of selected results with friends/peers. This will produce a unique URL for your selections to allow others to see the exact same graphs/results you have on screen.

If there are any issues with this then let me know, but I think it makes sense to have a chat about it tomorrow anyway prior to a merge just to make sure that there isn't anything else outstanding 👍 

James.

### CODE REVIEW

**Comment by ben-marshall** [comment]
Thanks for this! Unfortunately, I broke it....

I was on the comparison page, and selected on the RHS *first* `scale_lpc1313fbd48` and *then* on the LHS, the `cw308_stm32f1` target. I was then met by this message on the terminal:
```
Traceback (most recent call last):
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/work/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/work/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/work/scarv/miracle/miracle-browser/browser/api.py", line 21, in compare_experiments
    experiments = [g.db.row_to_dict(e) for e in list(set(experiments1) & set(experiments2))]
  File "/home/work/scarv/miracle/miracle-browser/browser/api.py", line 21, in <listcomp>
    experiments = [g.db.row_to_dict(e) for e in list(set(experiments1) & set(experiments2))]
AttributeError: 'SQLiteBackend' object has no attribute 'row_to_dict'
```

Do I need to pull some updates for the miracle-db as well?

Killing the server and refreshing the page worked fine, so it's possible it was the sequence in which I changed the target select boxes. I can't remember what it was, but the previous two selected targets had *zero* corresponding experiments, which might be relevant.

**Comment by ben-marshall** [comment]
Okay, getting closer.

Hitting it with this URL `http://127.0.0.1:5000/compare/?t1=2&t2=6&e=1&c=1108,1109,1110,1111,1112,1113&t=1` causes the same exception, and gets me an error response page (attached).

Screenshot from 2020-09-02 09-12-27

**Comment by jwsi** [comment]
Sorry yes, I forgot to make my PR into miracle-db!

**Comment by jwsi** [comment]
If you checkout the feature/compare branch on miracle-db too, you should be rid of those errrors 👍

**Comment by ben-marshall** [comment]
Aha! Yes, that made it work. I'll have a proper look at both patches and we can talk about it in the meeting.

**Comment by ben-marshall** [comment]
Okay, remembering from the meeting, three extra features:
- [x] Select all/none buttons for each target listing table. I.e. one for target 1 HW/HD, one for target 1 ttrace, one for target 2 etc.
- [x] A toggle button to allow *either* plotting all target results over on one axis, *or* plotting target 1 series on one axis, and target 2 series on another axis. Ideally have the axes above/below one another, not side by side.
- [x] Is there a way to have a "I'm busy doing something" spinner to show the request has been sent? This is only a *very nice to have* though.

**Comment by jwsi** [comment]
Hey @ben-marshall,

The first two tasks should be pretty simple to implement and I'll get cracking on that now.

With regards to the loading spinner, where would you like this to show? Is it after the plot button is clicked or in between every selection update?

James.

**Comment by ben-marshall** [comment]
> With regards to the loading spinner, where would you like this to show? Is it after the plot button is clicked or in between every selection update?

I'd say both if it isn't too complicated?

**Comment by jwsi** [comment]
Hi Ben,

I've pushed all the code to https://miracle.scarv.org now for testing. Would you mind letting me know if that kind of thing is what you had in mind with regards to the buttons and spinners?

I've also setup some scripts now for auto deploying to AWS, would you like a copy of those so you can put them in the repo somewhere? Perhaps useful under the bin folder?

**Comment by ben-marshall** [comment]
Hi James
Looks excellent! That's exactly what I had in mind. Is the "plot over/side-by-side" button there?
Yeah, the deploy scripts in the bin folder would be very helpful. I guess that as long as we keep our keys out of the repo, there's no problem with the deploy scripts being public eventually?
Cheers,
Ben

**Comment by jwsi** [comment]
Ok I'll add that in to the bin folder. No there's no issue in this being public as it'll require an SSH key to work anyway.

I have the new plot buttons in my working tree. However, I can't shake off a matplotlib error at the moment, it seems to be caused by my string serialisation logic as it's struggling to reconstruct the PNG with separate axes on the website end at the moment. But as soon as this is fixed it'll be in the PR here.

**Comment by jwsi** [comment]
Hey @ben-marshall,

I've just pushed an update to this PR which introduces buttons to allow for separate or mixed plots between respective targets. Would you mind having a go with it and letting me know what you think? For example, things like image size can be changed. So if there is anything you'd like altering just let me know.

**Review by ben-marshall — APPROVED** [review]

**Comment by ben-marshall** [comment]
Thanks @jwsi , this is ideal! Any changes to image size or the like I can do as and when. I will spend my pedantry budget elsewhere.

**Pull request merged**
